### ISSUE TITLE
Please include Redis create user command

### ISSUE THREAD

**Issue by mariusa** [Michael-Gibbons/OSB#82]
Hi, would you please include the Redis create user command in the install?

I don't know what permissions are required.

Thanks

**Comment by Michael-Gibbons** [comment]
@mariusa This template does not use redis directly, it uses redis as the engine to power bullmq. https://docs.bullmq.io/

If you need to access redis commands directly you can install a dedicated redis client package. Since that is related to the business logic of your application it is out of the scope of this template. Thanks

**Comment by Michael-Gibbons** [comment]
https://www.npmjs.com/package/redis
